// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmR35pkYGRwqh68977-73CZZLjaJJFErE',
    appId: '1:1069815825405:web:cb0b343de77107fc73cf94',
    messagingSenderId: '1069815825405',
    projectId: 'touristgeofence',
    authDomain: 'touristgeofence.firebaseapp.com',
    storageBucket: 'touristgeofence.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmR35pkYGRwqh68977-73CZZLjaJJFErE',
    appId: '1:1069815825405:android:cb0b343de77107fc73cf94',
    messagingSenderId: '1069815825405',
    projectId: 'touristgeofence',
    storageBucket: 'touristgeofence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmR35pkYGRwqh68977-73CZZLjaJJFErE',
    appId: '1:1069815825405:ios:cb0b343de77107fc73cf94',
    messagingSenderId: '1069815825405',
    projectId: 'touristgeofence',
    storageBucket: 'touristgeofence.firebasestorage.app',
    iosBundleId: 'com.example.tourist_geo_fencing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmR35pkYGRwqh68977-73CZZLjaJJFErE',
    appId: '1:1069815825405:macos:cb0b343de77107fc73cf94',
    messagingSenderId: '1069815825405',
    projectId: 'touristgeofence',
    storageBucket: 'touristgeofence.firebasestorage.app',
    iosBundleId: 'com.example.tourist_geo_fencing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmR35pkYGRwqh68977-73CZZLjaJJFErE',
    appId: '1:1069815825405:windows:cb0b343de77107fc73cf94',
    messagingSenderId: '1069815825405',
    projectId: 'touristgeofence',
    authDomain: 'touristgeofence.firebaseapp.com',
    storageBucket: 'touristgeofence.firebasestorage.app',
  );
}
